name: iclavis
description: Aplicación para el proyecto Guía Propietario.

version: 2.0.0+0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  amazon_cognito_identity_dart_2: ^3.0.0
  analyzer: ^4.6.0
  basic_utils: ^5.1.1
  bloc: ^8.1.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.1.1
  chewie: ^1.3.4
  connectivity_plus: ^2.3.6
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_analytics: ^10.0.2
  firebase_core: ^2.1.0
  firebase_core_web: ^2.0.0
  firebase_crashlytics: ^3.0.2
  firebase_messaging: ^14.1.4
  flutter_bloc: ^8.1.1
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.3.0
  flutter_html: ^3.0.0-alpha.5
  flutter_i18n: ^0.32.4
  flutter_local_notifications: ^13.0.0
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hydrated_bloc: ^9.0.0-dev.3
  image_picker: ^0.8.6
  image_picker_for_web: ^2.1.10
  open_filex: ^4.3.2
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  pin_code_fields: ^7.4.0
  rive: ^0.9.1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  video_player: ^2.4.7
  liquid_pull_to_refresh: ^3.0.1
  package_info_plus: ^3.0.2
  file_picker: ^5.2.4
  flutter_linkify: ^5.0.2
  charcode: ^1.3.1
  auto_size_text: ^3.0.0
  flutter_app_badger: ^1.5.0
  collection: ^1.16.0
  intl: ^0.17.0
  device_preview: ^1.1.0
  go_router: ^6.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.11.0
  very_good_analysis: ^3.1.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  #PNG 512x512
  #flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/custom.ttf
    - family: FaqsIcon
      fonts:
        - asset: assets/icons/faqsIcon.ttf

  assets:
    - assets/i18n/
    - assets/images/
    - assets/animations/
