// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4mbcu6yfAIeuq1HU_45Lvh3AfrLOJQlE',
    appId: '1:842512010768:web:99517f1be73c1e070c4495',
    messagingSenderId: '842512010768',
    projectId: 'guia-propietario',
    authDomain: 'guia-propietario.firebaseapp.com',
    databaseURL: 'https://guia-propietario.firebaseio.com',
    storageBucket: 'guia-propietario.appspot.com',
    measurementId: 'G-6LFJLQD197',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmULVSe-ew1IehUBkFUuVEb-fw6spo3OE',
    appId: '1:842512010768:android:acb2a55da72dafa90c4495',
    messagingSenderId: '842512010768',
    projectId: 'guia-propietario',
    databaseURL: 'https://guia-propietario.firebaseio.com',
    storageBucket: 'guia-propietario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA99w95nLnGQg_p5SjsiOqpPKch0qEiJI8',
    appId: '1:842512010768:ios:af1028cbfdf29e4b0c4495',
    messagingSenderId: '842512010768',
    projectId: 'guia-propietario',
    databaseURL: 'https://guia-propietario.firebaseio.com',
    storageBucket: 'guia-propietario.appspot.com',
    iosClientId: '842512010768-jbq6tag17fekkdoprslaa0egro7nkk7a.apps.googleusercontent.com',
    iosBundleId: 'com.planok.guia-propietario',
  );
}
