name: On Website Deploy
"on":
  push:
    # (1)
    branches:
      - "main"
jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest
    # (2)
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: 🌍 Enable Web
        run: flutter config --enable-web

      - name: 📦 Get packages
        run: flutter pub get

      - name: 🏭 Build Web Application
        run: flutter build web --release --dart-define COUNTRY_CODE=${{ secrets.COUNTRY_CODE }} --dart-define AWS_USER_POOL_ID=${{ secrets.AWS_USER_POOL_ID }} --dart-define AWS_CLIENT_ID=${{ secrets.AWS_CLIENT_ID }} --dart-define AWS_CLIENT_SECRET=${{ secrets.AWS_CLIENT_SECRET }} --dart-define GCI_API=${{ secrets.GCI_API }} --dart-define PLANOK_API=${{ secrets.PLANOK_API }} --dart-define PVI_API=${{ secrets.PVI_API }} --dart-define APP_CODE=${{ secrets.APP_CODE }} --dart-define SHARED_SECRET=${{ secrets.SHARED_SECRET }} --dart-define API_KEY=${{ secrets.API_KEY }}

      # (3)
      - name: Make copy of artifacts
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
          bash "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
      # (4)
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit the artifacts.
